version: "3.9"

services:
  app:
    build: 
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
     sh -c "python manage.py runserver 0.0.0.0:8000"


#  ржПржХ рж▓рж╛ржЗржирзЗ ржкрзБрж░рзЛ ржлрж╛ржЗрж▓ ржХрзА ржХрж░ржЫрзЗ?

# Dockerfile ржжрж┐рзЯрзЗ image ржмрж╛ржирж╛ржЪрзНржЫрзЗ

# Port expose ржХрж░ржЫрзЗ

# Local code mount ржХрж░ржЫрзЗ

# Django development server ржЪрж╛рж▓рж╛ржЪрзНржЫрзЗ

# ржЧрзБрж░рзБрждрзНржмржкрзВрж░рзНржг Developer Note ЁЯФе

# ржПржЯрж╛ рж╢рзБржзрзБ development setupред

# Production ржП:

# runserver ржмрзНржпржмрж╣рж╛рж░ ржХрж░рж╛ рж╣рзЯ ржирж╛

# gunicorn ржмрзНржпржмрж╣рж╛рж░ рж╣рзЯ

# nginx рж▓рж╛ржЧрзЗ

# debug off ржерж╛ржХрзЗ